// Powered by OnSpace.AI
import { Song } from '../services/songService';

export const MOCK_SONGS: Song[] = [
  {
    id: 'song-1',
    title: 'Bohemian Rhapsody',
    artist: 'Queen',
    albumArt: 'https://picsum.photos/seed/queen/300/300.webp',
    duration: 355,
    difficulty: 'Hard',
    genre: 'Rock',
    rating: 4.9,
    playCount: 15420,
    lyrics: 'Is this the real life? Is this just fantasy?...',
    backingTrackUrl: 'https://example.com/backing-tracks/bohemian-rhapsody.mp3',
    createdAt: '2024-01-01T00:00:00Z',
  },
  {
    id: 'song-2',
    title: 'Sweet Caroline',
    artist: 'Neil Diamond',
    albumArt: 'https://picsum.photos/seed/diamond/300/300.webp',
    duration: 201,
    difficulty: 'Medium',
    genre: 'Pop',
    rating: 4.7,
    playCount: 8930,
    lyrics: 'Where it began, I can\'t begin to knowing...',
    backingTrackUrl: 'https://example.com/backing-tracks/sweet-caroline.mp3',
    createdAt: '2024-01-02T00:00:00Z',
  },
  {
    id: 'song-3',
    title: 'Imagine',
    artist: 'John Lennon',
    albumArt: 'https://picsum.photos/seed/lennon/300/300.webp',
    duration: 183,
    difficulty: 'Easy',
    genre: 'Pop',
    rating: 4.8,
    playCount: 12350,
    lyrics: 'Imagine there\'s no heaven...',
    backingTrackUrl: 'https://example.com/backing-tracks/imagine.mp3',
    createdAt: '2024-01-03T00:00:00Z',
  },
  {
    id: 'song-4',
    title: 'Don\'t Stop Me Now',
    artist: 'Queen',
    albumArt: 'https://picsum.photos/seed/queen2/300/300.webp',
    duration: 209,
    difficulty: 'Medium',
    genre: 'Rock',
    rating: 4.6,
    playCount: 9870,
    lyrics: 'Tonight I\'m gonna have myself a real good time...',
    backingTrackUrl: 'https://example.com/backing-tracks/dont-stop-me-now.mp3',
    createdAt: '2024-01-04T00:00:00Z',
  },
  {
    id: 'song-5',
    title: 'Perfect',
    artist: 'Ed Sheeran',
    albumArt: 'https://picsum.photos/seed/sheeran/300/300.webp',
    duration: 263,
    difficulty: 'Medium',
    genre: 'Pop',
    rating: 4.5,
    playCount: 18200,
    lyrics: 'I found a love for me...',
    backingTrackUrl: 'https://example.com/backing-tracks/perfect.mp3',
    createdAt: '2024-01-05T00:00:00Z',
  },
  {
    id: 'song-6',
    title: 'My Way',
    artist: 'Frank Sinatra',
    albumArt: 'https://picsum.photos/seed/sinatra/300/300.webp',
    duration: 275,
    difficulty: 'Hard',
    genre: 'Jazz',
    rating: 4.9,
    playCount: 7650,
    lyrics: 'And now, the end is near...',
    backingTrackUrl: 'https://example.com/backing-tracks/my-way.mp3',
    createdAt: '2024-01-06T00:00:00Z',
  },
  {
    id: 'song-7',
    title: 'Shape of You',
    artist: 'Ed Sheeran',
    albumArt: 'https://picsum.photos/seed/sheeran2/300/300.webp',
    duration: 233,
    difficulty: 'Easy',
    genre: 'Pop',
    rating: 4.4,
    playCount: 22100,
    lyrics: 'The club isn\'t the best place to find a lover...',
    backingTrackUrl: 'https://example.com/backing-tracks/shape-of-you.mp3',
    createdAt: '2024-01-07T00:00:00Z',
  },
  {
    id: 'song-8',
    title: 'Hotel California',
    artist: 'Eagles',
    albumArt: 'https://picsum.photos/seed/eagles/300/300.webp',
    duration: 391,
    difficulty: 'Hard',
    genre: 'Rock',
    rating: 4.8,
    playCount: 11420,
    lyrics: 'On a dark desert highway, cool wind in my hair...',
    backingTrackUrl: 'https://example.com/backing-tracks/hotel-california.mp3',
    createdAt: '2024-01-08T00:00:00Z',
  },
];

export const MOCK_LEADERBOARD = [
  {
    id: 'user-1',
    displayName: 'Melody Master',
    photoURL: 'https://picsum.photos/seed/user1/150/150.webp',
    krtBalance: 15420,
    rank: 'Diamond',
    totalScore: 98750,
    songsCompleted: 145,
  },
  {
    id: 'user-2',
    displayName: 'Vocal Virtuoso',
    photoURL: 'https://picsum.photos/seed/user2/150/150.webp',
    krtBalance: 12350,
    rank: 'Platinum',
    totalScore: 87650,
    songsCompleted: 132,
  },
  {
    id: 'user-3',
    displayName: 'Rhythm Ruler',
    photoURL: 'https://picsum.photos/seed/user3/150/150.webp',
    krtBalance: 9870,
    rank: 'Gold',
    totalScore: 76420,
    songsCompleted: 98,
  },
  {
    id: 'demo-user-1',
    displayName: 'Demo User',
    photoURL: 'https://picsum.photos/seed/user/150/150.webp',
    krtBalance: 1250,
    rank: 'Gold',
    totalScore: 15420,
    songsCompleted: 23,
  },
];

export const MOCK_BATTLES = [
  {
    id: 'battle-1',
    name: 'Friday Night Showdown',
    description: 'Weekly battle featuring the hottest pop hits',
    song: MOCK_SONGS[4], // Perfect by Ed Sheeran
    participants: 24,
    prizePool: 2500,
    status: 'active',
    endTime: new Date(Date.now() + 2 * 60 * 60 * 1000).toISOString(), // 2 hours from now
  },
  {
    id: 'battle-2',
    name: 'Rock Legends Battle',
    description: 'Classic rock battle for true legends',
    song: MOCK_SONGS[0], // Bohemian Rhapsody
    participants: 18,
    prizePool: 1800,
    status: 'active',
    endTime: new Date(Date.now() + 5 * 60 * 60 * 1000).toISOString(), // 5 hours from now
  },
];

export const MOCK_PERFORMANCES = [
  {
    id: 'performance-1',
    userId: 'demo-user-1',
    songId: 'song-1',
    score: 87,
    accuracy: 0.89,
    timing: 0.85,
    pitch: 0.88,
    krtEarned: 87,
    recordedAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(), // 2 hours ago
  },
  {
    id: 'performance-2',
    userId: 'demo-user-1',
    songId: 'song-2',
    score: 92,
    accuracy: 0.94,
    timing: 0.90,
    pitch: 0.92,
    krtEarned: 115,
    recordedAt: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(), // 1 day ago
  },
];

export default {
  MOCK_SONGS,
  MOCK_LEADERBOARD,
  MOCK_BATTLES,
  MOCK_PERFORMANCES,
};